// this file contains the initial state values for the Residence History form

const rhInitialValues = {
    rhCurrentAddress: '',
    rhCurrentCity: '',
    rhCurrentState: '',
    rhCurrentZip: '',
    rhCurrentLandlord: '',
    rhCurrentLandlordPhone: '',
    rhCurrentReasonForLeaving: '',
    rhCurrentMonthlyRent: '',
    rhCurrentFromMonth: '',
    rhCurrentFromDay: '',
    rhCurrentFromYear: '',
    rhCurrentToMonth: '',
    rhCurrentToDay: '',
    rhCurrentToYear: '',

    rhPreviousAddress1: '',
    rhPreviousCity1: '',
    rhPreviousState1: '',
    rhPreviousZip1: '',
    rhPreviousLandlord1: '',
    rhPreviousLandlordPhone1: '',
    rhPreviousReasonForLeaving1: '',
    rhPreviousMonthlyRent1: '',
    rhPreviousFromMonth1: '',
    rhPreviousFromDay1: '',
    rhPreviousFromYear1: '',
    rhPreviousToMonth1: '',
    rhPreviousToDay1: '',
    rhPreviousToYear1: '',

    rhPreviousAddress2: '',
    rhPreviousCity2: '',
    rhPreviousState2: '',
    rhPreviousZip2: '',
    rhPreviousLandlord2: '',
    rhPreviousLandlordPhone2: '',
    rhPreviousReasonForLeaving2: '',
    rhPreviousMonthlyRent2: '',
    rhPreviousFromMonth2: '',
    rhPreviousFromDay2: '',
    rhPreviousFromYear2: '',
    rhPreviousToMonth2: '',
    rhPreviousToDay2: '',
    rhPreviousToYear2: '',
}
 
export default rhInitialValues;