import * as yup from "yup";

const rhValidationSchema = yup.object().shape({
	rhCurrentAddress: yup.string().required('Required'),
    rhCurrentCity: yup.string().required('Required'),
    rhCurrentState: yup.string().required('Required'),
    rhCurrentZip: yup.string().required('Required'),
    rhCurrentLandlord: yup.string().required('Required'),
    rhCurrentLandlordPhone: yup.string().required('Required'),
    rhCurrentReasonForLeaving: yup.string().required('Required'),
    rhCurrentMonthlyRent: yup.string().required('Required'),
    rhCurrentFromMonth: yup.string().required('Required'),
    rhCurrentFromDay: yup.string().required('Required'),
    rhCurrentFromYear: yup.string().required('Required'),
    rhCurrentToMonth: yup.string().required('Required'),
    rhCurrentToDay: yup.string().required('Required'),
    rhCurrentToYear: yup.string().required('Required'),

    rhPreviousAddress1: '',
    rhPreviousCity1: '',
    rhPreviousState1: '',
    rhPreviousZip1: '',
    rhPreviousLandlord1: '',
    rhPreviousLandlordPhone1: '',
    rhPreviousReasonForLeaving1: '',
    rhPreviousMonthlyRent1: '',
    rhPreviousFromMonth1: '',
    rhPreviousFromDay1: '',
    rhPreviousFromYear1: '',
    rhPreviousToMonth1: '',
    rhPreviousToDay1: '',
    rhPreviousToYear1: '',

    rhPreviousAddress2: '',
    rhPreviousCity2: '',
    rhPreviousState2: '',
    rhPreviousZip2: '',
    rhPreviousLandlord2: '',
    rhPreviousLandlordPhone2: '',
    rhPreviousReasonForLeaving2: '',
    rhPreviousMonthlyRent2: '',
    rhPreviousFromMonth2: '',
    rhPreviousFromDay2: '',
    rhPreviousFromYear2: '',
    rhPreviousToMonth2: '',
    rhPreviousToDay2: '',
    rhPreviousToYear2: '',
});

export default rhValidationSchema;